# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acquisition.ui',
# licensing of 'acquisition.ui' applies.
#
# Created: Mon Feb 10 15:21:00 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_acquisition(object):
    def setupUi(self, acquisition):
        acquisition.setObjectName("acquisition")
        acquisition.resize(1138, 665)
        self.acquisition_layout = QtWidgets.QHBoxLayout(acquisition)
        self.acquisition_layout.setSpacing(0)
        self.acquisition_layout.setContentsMargins(0, 0, 0, 0)
        self.acquisition_layout.setObjectName("acquisition_layout")
        self.controls = QtWidgets.QFrame(acquisition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controls.sizePolicy().hasHeightForWidth())
        self.controls.setSizePolicy(sizePolicy)
        self.controls.setMinimumSize(QtCore.QSize(480, 0))
        self.controls.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controls.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controls.setObjectName("controls")
        self.dockWidget = QtWidgets.QDockWidget(self.controls)
        self.dockWidget.setGeometry(QtCore.QRect(90, 470, 120, 80))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.acquisition_layout.addWidget(self.controls)
        self.viewer = QtWidgets.QFrame(acquisition)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer.sizePolicy().hasHeightForWidth())
        self.viewer.setSizePolicy(sizePolicy)
        self.viewer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewer.setObjectName("viewer")
        self.viewer_layout = QtWidgets.QGridLayout(self.viewer)
        self.viewer_layout.setSpacing(0)
        self.viewer_layout.setContentsMargins(0, 0, 0, 0)
        self.viewer_layout.setObjectName("viewer_layout")
        self.viewer_layout_2 = QtWidgets.QHBoxLayout()
        self.viewer_layout_2.setObjectName("viewer_layout_2")
        self.view_type = QtWidgets.QFrame(self.viewer)
        self.view_type.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.view_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.view_type.setObjectName("view_type")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.view_type)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.view_2d = QtWidgets.QToolButton(self.view_type)
        self.view_2d.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/acquisition/2d"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_2d.setIcon(icon)
        self.view_2d.setIconSize(QtCore.QSize(36, 36))
        self.view_2d.setAutoRaise(True)
        self.view_2d.setObjectName("view_2d")
        self.verticalLayout_2.addWidget(self.view_2d)
        self.view_2d_mip = QtWidgets.QToolButton(self.view_type)
        self.view_2d_mip.setText("")
        self.view_2d_mip.setIcon(icon)
        self.view_2d_mip.setIconSize(QtCore.QSize(36, 36))
        self.view_2d_mip.setAutoRaise(True)
        self.view_2d_mip.setObjectName("view_2d_mip")
        self.verticalLayout_2.addWidget(self.view_2d_mip)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.viewer_layout_2.addWidget(self.view_type)
        self.navigable_canvas = QtWidgets.QFrame(self.viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigable_canvas.sizePolicy().hasHeightForWidth())
        self.navigable_canvas.setSizePolicy(sizePolicy)
        self.navigable_canvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigable_canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigable_canvas.setObjectName("navigable_canvas")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.navigable_canvas)
        self.verticalLayout.setObjectName("verticalLayout")
        self.canvas = QtWidgets.QWidget(self.navigable_canvas)
        self.canvas.setMinimumSize(QtCore.QSize(512, 512))
        self.canvas.setObjectName("canvas")
        self.verticalLayout.addWidget(self.canvas)
        self.navigation = QtWidgets.QFrame(self.navigable_canvas)
        self.navigation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navigation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navigation.setObjectName("navigation")
        self.verticalLayout.addWidget(self.navigation)
        self.viewer_layout_2.addWidget(self.navigable_canvas)
        self.viewer_layout.addLayout(self.viewer_layout_2, 0, 0, 1, 1)
        self.acquisition_layout.addWidget(self.viewer)

        self.retranslateUi(acquisition)
        QtCore.QMetaObject.connectSlotsByName(acquisition)

    def retranslateUi(self, acquisition):
        acquisition.setWindowTitle(QtWidgets.QApplication.translate("acquisition", "Form", None, -1))
        self.view_2d.setToolTip(QtWidgets.QApplication.translate("acquisition", "2D", None, -1))
        self.view_2d_mip.setToolTip(QtWidgets.QApplication.translate("acquisition", "2D MIP", None, -1))

from . import resources_rc
